---
# OCM Component Settings
# This file provides default values for building the CloudNativePG OCM component.
# Values can be overridden via environment variables or command-line arguments.

# Component Metadata
COMPONENT_NAME: "ocm.software/cloudnative-pg"
PROVIDER_NAME: "ocm.software"

# CloudNativePG Operator Version
# See: https://github.com/cloudnative-pg/cloudnative-pg/releases
CNPG_VERSION: "1.24.1"

# PostgreSQL Versions
# See: https://github.com/cloudnative-pg/postgres-containers/pkgs/container/postgresql
# Note: Using simple two-part versions
PG_VERSION_17: "17"
PG_VERSION_16: "16"
PG_VERSION_15: "15"
PG_VERSION_14: "14"

# Note: PostgreSQL version 16 is marked as the default version in the component descriptor

# Extension Versions (for component references)
# PostGIS version follows format: <pg_version>-<postgis_version>
POSTGIS_VERSION: "16-3.4"
