---
# OCM Component Settings
# This file provides default values for building the CloudNativePG OCM component.
# Values can be overridden via environment variables or command-line arguments.

# Component Metadata
COMPONENT_NAME: "ocm.software/cloudnative-pg"
PROVIDER_NAME: "ocm.software"

# CloudNativePG Operator Version
# See: https://github.com/cloudnative-pg/cloudnative-pg/releases
CNPG_VERSION: "1.24.1"

# PostgreSQL Versions
# See: https://github.com/cloudnative-pg/postgres-containers/pkgs/container/postgresql
PG_VERSION_17: "17.2"
PG_VERSION_16: "16.6"
PG_VERSION_15: "15.10"
PG_VERSION_14: "14.15"

# Note: PostgreSQL version 16 is marked as the default version in the component descriptor
